ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
OLED_DRIVER_ENABLE = yes
OLED_ENABLE = yes
WPM_ENABLE = yes

AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = no
COMBO_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
KEY_LOCK_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
STENO_ENABLE = no
TAP_DANCE_ENABLE = no
UNICODE_ENABLE = no

EXTRAFLAGS += -flto

WPM_SMOOTHING = 0.0243
